CREATE TABLE PersonalSite.Accounts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DisplayName VARCHAR(64) CHARACTER SET utf8mb4,
    Username VARCHAR(64) NOT NULL CHARACTER SET utf8mb4,
    PasswordHash VARCHAR(64) NOT NULL,
) CHARACTER SET utf8mb4;